spring:
  application:
  name: taskmanagerauth
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: # no password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# Logging
logging:
  level:
    root: "INFO"
  file:
    name: "logs/application.log"
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%t] %p %c{36} - %m%n"

server:
  port: 9095
  servlet:
    context-path: "/api"
  ssl:
    key-store: "/home/ubuntu/taskmanagerauth/springboot.p12"
    key-store-password: "admin"
    key-store-type: PKCS12
    key-alias: springboot

jwt:
  secret: "Test"

frontend:
  location: "http://localhost:3000"